config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'relationships/followings'
    get 'relationships/followers'
  end
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  scope module: :public do
    root :to => 'homes#top'

    get 'users/withdraw' => 'users#withdraw'
    patch 'users/unsubscribe' => 'users#unsubscribe'
    post 'reviews/confirm' => 'reviews#confirm'
    get 'reviews/confirm' => 'reviews#confirm'
    get 'reviews/complete' => 'reviews#complete'


    resources :books, only: [:index, :show]
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
    end
    resources :reviews, only: [:new, :create, :index, :destroy] do
      resource :review_likes, only: [:create, :destroy]
    end

    resources :books, except: [:index] do
      resource :bookmarks, only: [:create, :destroy]
    end
  end

  namespace :admin do
    root :to => 'users#index'
    resources :users, only: [:index, :show, :edit, :update]
    resources :reviews, only: [:index, :show, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @reviews = Review.all.order(created_at: :asc).page(params[:page]).per(9)
  end

  def show
    @review = Review.find(params[:id])
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to admin_reviews_path
  end
 private

  def book_params
    params.require(:book).permit(:title, :isbn, :author, :image_url, :item_url)
  end

  def review_params
    params.require(:review).permit(:user_id, :book_id, :content, :rate)
  end

end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/views/admin/reviews/index.html.erb
<div class="admin_index mx-auto">
 <h4 class="text pt-3">
   <i class="fas fa-comments"></i>
    レビュー一覧
 </h4>
 <table class='table w-90 mx-auto table-hover table-inverse'>
  <thead>
   <tr class="text">
    <th>作成日時</th>
    <th class="pl-3">ユーザーネーム</th>
    <th class="pl-5">レビュー内容</th>
   </tr>
  </thead>
  <tbody>
    <% @reviews.each do |review| %>
     <tr class="text">
       <td><%= link_to review.created_at.strftime("%Y/%m/%d %H:%M:%S"),admin_review_path(review) %></td>
       <td class="pl-3"><%= review.user.user_name %></td>
       <td class="pl-5"><%= truncate(review.content, length: 40, omission: "[...]") %></td>
     </tr>
    <% end %>
  </tbody>
 </table>
 <div class="pagination d-flex justify-content-center mt-3">
     <%= paginate @reviews, theme: 'bootstrap-5' %>
 </div>
</div>

app/views/admin/reviews/show.html.erb
<h4 class="w-75 mx-auto text py-3"><%= @review.user.user_name %>さんのレビュー詳細</h4>
  <table class='table w-75 mx-auto'>
    <colgroup>
      <col class="col-md-4">
      <col class="col-md-7">
    </colgroup>
    <tbody>
      <tr class="text">
        <th>作成日時</th>
        <th><%= @review.created_at.strftime("%Y/%m/%d %H:%M:%S") %></th>
      </tr>
      <tr class="text">
        <th>ユーザーネーム</th>
        <th><%= @review.user.user_name %></th>
      </tr>
      <tr class="text">
        <th>本のタイトル</th>
        <th><%= @review.book.title %></th>
      </tr>
      <tr class="text">
        <th>レビュー内容</th>
        <th><%= simple_format(@review.content) %></th>
      </tr>
      <tr class="text">
        <th></th>
        <th><%= link_to '削除する', admin_review_path(@review), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger" %></th>
      </tr>
    </tbody>
  </table>