config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'relationships/followings'
    get 'relationships/followers'
  end
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  scope module: :public do
    root :to => 'homes#top'

    get 'users/withdraw' => 'users#withdraw'
    patch 'users/unsubscribe' => 'users#unsubscribe'
    post 'reviews/confirm' => 'reviews#confirm'
    get 'reviews/confirm' => 'reviews#confirm'
    get 'reviews/complete' => 'reviews#complete'


    resources :books, only: [:index, :show]
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
    end
    resources :reviews, only: [:new, :create, :index, :destroy] do
      resource :review_likes, only: [:create, :destroy]
    end

    resources :books, except: [:index] do
      resource :bookmarks, only: [:create, :destroy]
    end
  end

  namespace :admin do
    root :to => 'users#index'
    resources :users, only: [:index, :show, :edit, :update]
    resources :reviews, only: [:index, :show, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  has_many :bookmarks, dependent: :destroy
  has_many :books, through: :favorite_books, source: :book
  has_many :reviews, dependent: :destroy
  has_many :review_likes, dependent: :destroy
  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def bookmarks(book)
    self.favorites.find_or_create_by(book_id: book.id)
  end

  def bookmarks(book)
    favorite = self.favorites.find_by(book_id: book.id)
    favorite.destroy if favorite
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.png')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.png', content_type: 'image/png')
    end
    profile_image.variant(resize_to_fill: [width, height]).processed
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :authentication_keys => [:user_name]

  validates :user_name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 10 }
  validate :verify_file_type

  enum gender: { male: 0, female: 1, no_answer:2 }


  validates :birth_date, presence: true

  def age_group
    age = Time.zone.today.year - birth_date.year
    case age
    when 10..19
      '10代'
    when 20..29
      '20代'
    when 30..39
      '30代'
    when 40..49
      '40代'
    when 50..59
      '50代'
    else
      '60代以上'
    end
  end

  private
  def verify_file_type
    return unless profile_image.attached?  # ②

    allowed_file_types = %w[image/jpg image/jpeg image/gif image/png]  # ③
    errors.add(:profile_image, 'only jpg, jpeg, gif, png') unless allowed_file_types.include?(profile_image.blob.content_type)  # ④
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all.page(params[:page]).per(9)
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user)
    else
      render edit
    end
  end

  private
  def user_params
    params.require(:user).permit( :image, :email, :password, :user_name, :gender, :birth_date, :is_deleted)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<h4 class="w-75 mx-auto text py-3"><%= @user.user_name %>さんの会員情報編集</h4>
 <%= form_with model:@user, url:admin_user_path(@user), method: :patch, local: true do |f| %>
  <table class='table w-75 mx-auto'>
    <colgroup>
      <col class="col-md-4">
      <col class="col-md-7">
    </colgroup>
    <tbody>
      <tr class="text">
        <th>会員ID</th>
        <th><%= @user.id %></th>
      </tr>
      <tr class="text">
        <th>ユーザーネーム</th>
        <th><%= @user.user_name %></th>
      </tr>
      <tr class="text">
        <th>年代</th>
        <th><%= @user.age_group %></th>
      </tr>
      <tr class="text">
        <th>性別</th>
        <th><%= @user.gender_i18n %></th>
      </tr>
      <tr class="text">
        <th>メールアドレス</th>
        <th><%= @user.email %></th>
      </tr>
      <tr class="text">
        <th><label for="user_is_deleted">会員ステータス</label></th>
        <th>
          <%= f.label :is_deleted, for: "deleted_true" do %>
            <%= f.radio_button :is_deleted, true, id: "deleted_true" %>
            退会
          <% end %>

          <%= f.label :is_deleted, for: "deleted_false" do %>
            <%= f.radio_button :is_deleted, false, id: "deleted_false" %>
            有効
          <% end %>
        </th>
      </tr>
      <tr class="text">
        <th></th>
        <th><%= f.submit '変更を保存',class: 'btn btn-warning' %></th>
      </tr>
    </tbody>
  </table>
 <% end %>

app/views/admin/users/index.html.erb
<div class="admin_index mx-auto">
 <h4 class="text pt-3">
   <i class="fas fa-users"></i>
   会員一覧
 </h4>
 <table class='table table-hover table-inverse'>
     <colgroup>
       <col class="col-md-2">
       <col class="col-md-3">
       <col class="col-md-4">
       <col class="col-md-2">
     </colgroup>
     <thead>
      <tr class="text">
       <th>会員ID</th>
       <th>氏名</th>
       <th>メールアドレス</th>
       <th>ステータス</th>
      </tr>
     </thead>
   <tbody>
     <% @users.each do |user| %>
      <tr class="text">
        <td><%= user.id %></td>
        <td><%= link_to user.user_name,admin_user_path(user) %></td>
        <td><%= user.email %></td>
        <td class="mx-auto"><%= user.is_deleted ? '退会' : '有効' %></td>
      </tr>
     <% end %>
   </tbody>
 </table>
 <div class="pagination d-flex justify-content-center mt-3">
     <%= paginate @users, theme: 'bootstrap-5' %>
 </div>
</div>

app/views/admin/users/show.html.erb
<h4 class="w-75 mx-auto text py-3"><%= @user.user_name %>さんの会員詳細</h4>
  <table class='table w-75 mx-auto'>
    <colgroup>
      <col class="col-md-5">
      <col class="col-md-6">
    </colgroup>
    <tbody>
      <tr class="text">
        <th>会員ID</th>
        <th><%= @user.id %></th>
      </tr>
      <tr class="text">
        <th>ユーザーネーム</th>
        <th><%= @user.user_name %></th>
      </tr>
      <tr class="text">
        <th>年代</th>
        <th><%= @user.age_group %></th>
      </tr>
      <tr class="text">
        <th>性別</th>
        <th><%= @user.gender_i18n %></th>
      </tr>
      <tr class="text">
        <th>メールアドレス</th>
        <th><%= @user.email %></th>
      </tr>
      <tr class="text">
        <th>会員ステータス</th>
        <th><%= @user.is_deleted ? '退会' : '有効' %></th>
      </tr>
      <tr class="text">
        <th></th>
        <th><%= link_to '編集する', edit_admin_user_path(@user), class: "btn btn-sm btn-warning text px-2" %></th>
      </tr>
    </tbody>
  </table>