config/routes.rb
Rails.application.routes.draw do
  namespace :public do
    get 'relationships/followings'
    get 'relationships/followers'
  end
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  scope module: :public do
    root :to => 'homes#top'

    get 'users/withdraw' => 'users#withdraw'
    patch 'users/unsubscribe' => 'users#unsubscribe'
    post 'reviews/confirm' => 'reviews#confirm'
    get 'reviews/confirm' => 'reviews#confirm'
    get 'reviews/complete' => 'reviews#complete'


    resources :books, only: [:index, :show]
    resources :users, only: [:show, :edit, :update] do
      resource :relationships, only: [:create, :destroy]
    end
    resources :reviews, only: [:new, :create, :index, :destroy] do
      resource :review_likes, only: [:create, :destroy]
    end

    resources :books, except: [:index] do
      resource :bookmarks, only: [:create, :destroy]
    end
  end

  namespace :admin do
    root :to => 'users#index'
    resources :users, only: [:index, :show, :edit, :update]
    resources :reviews, only: [:index, :show, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg">
   <div class="container text mx-auto">
    <%= link_to root_path do %>
      <%= image_tag 'logo.png', size: '200x90' %>
    <% end %>
    <small>漫画を楽しむレビューサイト</small>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
     </button>
      <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav ml-auto">
          <!--会員がログインしているとき-->
          <% if user_signed_in? %>
            <div class="text ml-2 mr-5 mt-2">
              <%= form_with url: books_path, method: :get, local: true do |f| %>
                <%= f.text_field :search, placeholder: "漫画タイトルを検索" %>
                <%= f.submit "\uF002", class: 'fa_icon' %>
              <% end %>
            </div>
           <li>
             <%= link_to root_path, class: 'nav-link text' do %>
              <i class="fas fa-smile-wink fa-spin"></i>トップ
             <% end %>
           </li>
           <li>
             <%= link_to reviews_path,class: 'nav-link text' do %>
              <i class="fas fa-comments"></i>レビュー一覧
             <% end %>
           </li>
           <li>
             <%= link_to user_path(current_user),class: 'nav-link text' do %>
              <i class="fas fa-user"></i> マイページ
             <% end %>
           </li>
           <li>
             <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
             <% end %>
           </li>

          <!--管理者がログインしているとき-->
          <% elsif admin_signed_in? %>
           <li>
             <%= link_to admin_users_path,class: 'nav-link text' do %>
              <i class="fas fa-users"></i> ユーザー一覧
             <% end %>
           </li>
           <li>
             <%= link_to admin_reviews_path,class: 'nav-link text' do %>
              <i class="fas fa-comments"></i>レビュー一覧
             <% end %>
           </li>
           <li>
             <%= link_to destroy_admin_session_path, method: :delete,class: 'nav-link text' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
             <% end %>
           </li>

          <!--ログインしていないとき-->
          <% else %>
            <div class="text mr-5 mt-2">
              <%= form_with url: books_path, method: :get, local: true do |f| %>
                <%= f.text_field :search, placeholder: "漫画タイトルを検索" %>
                <%= f.submit "\uF002", class: 'fa_icon' %>
              <% end %>
            </div>
           <li>
             <%= link_to root_path, class: 'nav-link text' do %>
              <i class="fas fa-smile-wink fa-spin"></i>トップ
             <% end %>
           </li>
           <li>
             <%= link_to reviews_path,class: 'nav-link text' do %>
              <i class="fas fa-comments"></i>レビュー一覧
             <% end %>
           </li>
           <li>
             <%= link_to new_user_registration_path,class: 'nav-link text' do %>
              <i class="fas fa-user-plus"></i> 新規登録
             <% end %>
           </li>
           <li>
             <%= link_to new_user_session_path ,class: 'nav-link text' do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
             <% end %>
           </li>
          <% end %>
        </ul>
      </div>
   </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manga</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css"/>
    <script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>
    <link rel="/assets/stylesheets" href="public/homes.scss" />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-infinitescroll/2.1.0/jquery.infinitescroll.min.js"></script>

  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer class="manga_footer bg-white text text-right mt-3 py-3 pr-3">©2023 manganosusume</footer>
  </body>
</html>